postman:
    stage: test
    image:
        name: postman/newman_alpine33
        entrypoint: [""]
    script:
        - newman --version
        - newman run postman.json

backend:
    stage: test
    image: python
    script:
        - pip install -r backend/requirements.txt
        - make testbackend

frontend:
    stage: test
    script:
        - pwd

selenium:
    stage: test
    script:
        - pwd