postman:
    stage: test
    image:
        name: postman/newman_alpine33
        entrypoint: [""]
    script:
        - newman --version
        - newman run postman.json

backend:
    stage: test
    image: python
    script:
        - pip install -r backend/requirements.txt
        - make testbackend

frontend:
    stage: test
    image: node
    script:
        - cd frontend
        - yarn install
        - yarn run test

selenium:
    stage: test
    image: python
    script:
        - pwd
        - pip install selenium
        - pip install webdriver_manager
        - apt-get update -q -y
        - apt-get install nodejs npm -y
        - apt-get install -y libglib2.0-0=2.50.3-2 \
        libnss3=2:3.26.2-1.1+deb9u1 \
        libgconf-2-4=3.2.6-4+b1 \
        libfontconfig1=2.11.0-6.7+b1
        - cd frontend
        # - curl -o- -L https://yarnpkg.com/install.sh | bash
        - npm install
        - cd ..
        - cd test
        - chmod +x geckodriver
        - python3 test.py
