backend:
    stage: test
    image: python
    script: make testbackend

frontend:
    stage: test
    image: node
    script: make testfrontend

selenium:
    stage: test
    image: python
    script: make testselenium

postman:
    stage: test
    image:
        name: postman/newman_alpine33
        entrypoint: [""]
    script:
        - newman --version
        - newman run postman.json
