postman:
    stage: test
    image:
        name: postman/newman_alpine33
        entrypoint: [""]
    script:
        - newman --version
        - newman run postman.json

backend:
    stage: test
    image: python
    script:
        - pip install -r backend/requirements.txt
        - make testbackend

frontend:
    stage: test
    image: yarnpkg/node-yarn
    script:
        - cd frontend
        - yarn test

selenium:
    stage: test
    image: python
    script:
        - pip install selenium
        - make testui