backend:
    stage: test
    image: python
    script:
        - pip install -r backend/requirements.txt
        - make testbackend

postman:
    stage: test
    image: postman/newman_alpine33
    script:
        - newman --version
        - newman run postman.json