backend:
    stage: test
    script:
        - make testbackend

postman:
    stage: test
    image:
        name: postman/newman_alpine33
        entrypoint: [""]
    script:
        - newman --version
        - newman run postman.json